pipeline:

  build-debs:
    image: gcr.io/admobilize-testing/builder-qemu:latest
    privileged: true
    mountimg: ${MOUNTIMG}
    mountoffset: ${MOUNTOFFSET}
    body: |
      apt-get update
      apt-get install --yes cdbs debhelper autotools-dev texinfo texlive autotools-dev autoconf libjim-dev pkg-config dh-autoreconf
      ./configure && debuild -us -uc -b

matrix:
  include: 
    - CODENAME: jessie
      DISTRIBUTION: raspbian
      MOUNTOFFSET: 48234496
      MOUNTDIR: /drone/src/github.com/matrix-io/matrix-creator-openocd
      MOUNTIMG: https://storage.googleapis.com/raspbian-images/2017-07-05-raspbian-jessie-lite.img.gz
    #- CODENAME: stretch
    #  MOUNTOFFSET: 48234496
    #  MOUNTDIR: /drone/src/github.com/matrix-io/matrix-creator-openocd
    #  DISTRIBUTION: raspbian
    #  MOUNTIMG: https://storage.googleapis.com/raspbian-images/2017-08-16-raspbian-stretch-lite.img.gz
