#!/bin/sh
# Run the autotools bootstrap sequence to create the configure script

# Abort execution on error
set -e

if which libtoolize > /dev/null; then
    libtoolize="libtoolize"
elif which glibtoolize >/dev/null; then
    libtoolize="glibtoolize"
else
    echo "$0: Error: libtool is required" >&2
    exit 1
fi

if [ "$1" = "nosubmodule" ]; then
    SKIP_SUBMODULE=1
elif [ -n "$1" ]; then
    echo "$0: Illegal argument $1"
    echo "USAGE: $0 [nosubmodule]"
    exit 1
fi

# bootstrap the autotools
(
set -x
${libtoolize} --force --automake --copy
aclocal
autoheader
automake --force-missing --add-missing --gnu --copy
autoconf
)

if [ -n "$SKIP_SUBMODULE" ]; then
    echo "Skipping submodule setup"
else
    echo "Setting up submodules"
    git submodule init
    git submodule update
fi

echo "Bootstrap complete. Quick build instructions:"
echo "./configure ...."
